supermercado/config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'users/new'

  get 'usuario/new'
  resources :relatorios

  resources :produtos

  resources :funcionarios
  
  get  'welcome/about'
  

  root 'welcome#index'

end

supermercado/app/models/produto.rb
class Produto < ActiveRecord::Base
    has_many :relatorios
end

supermercado/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :validade, :marca, :peso)
    end
end

supermercado/app/helpers/produtos_helper.rb
module ProdutosHelper
end

supermercado/app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome, "Nome" %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :validade, "Validade" %><br>
    <%= f.text_field :validade %>
  </div>
  <div class="field">
    <%= f.label :marca, "Marca" %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :peso, "Peso"%><br>
    <%= f.text_field :peso %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

supermercado/app/views/produtos/edit.html.erb
<h1>Editando Produto</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @produto %> |
<%= link_to 'Voltar', produtos_path %>

supermercado/app/views/produtos/index.html.erb
<h1>Supervisor</h1>


<h1>Lista de Produtos</h1>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Validade</th>
      <th>Marca</th>
      <th>Peso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.validade %></td>
        <td><%= produto.marca %></td>
        <td><%= produto.peso %></td>
        <td><%= link_to 'Detalhes', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Remover', produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Novo Produto', new_produto_path %>

supermercado/app/views/produtos/new.html.erb
<h1>Novo Produto</h1>
<div class="center jumbotron">

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>
</div>

supermercado/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Validade:</strong>
  <%= @produto.validade %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @produto.marca %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @produto.peso %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>