supermercado/config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'users/new'

  get 'usuario/new'
  resources :relatorios

  resources :produtos

  resources :funcionarios
  
  get  'welcome/about'
  

  root 'welcome#index'

end

supermercado/app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
end

supermercado/app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario criado com sucesso. ' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario atualizado com sucesso. ' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario removido com sucesso. ' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :sexo, :email, :data, :idade, :salario)
    end
end

supermercado/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

supermercado/app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sexo, "Sexo" %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :data, "Data" %><br>
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :idade, "Idade" %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :salario, "Salario" %><br>
    <%= f.number_field :salario %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>
</div>
</div>

supermercado/app/views/funcionarios/edit.html.erb
<h1>Editar Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @funcionario %> |
<%= link_to 'Voltar', funcionarios_path %>

supermercado/app/views/funcionarios/index.html.erb
<h1>Administrador</h1>


<h1>Lista de Funcionarios</h1>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sexo</th>
      <th>Email</th>
      <th>Data</th>
      <th>Idade</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.sexo %></td>
        <td><%= funcionario.email %></td>
        <td><%= funcionario.data %></td>
        <td><%= funcionario.idade %></td>
        <td><%= funcionario.salario %></td>
        <td><%= link_to 'Detalhes', funcionario %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Remover', funcionario, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Novo Funcionario', new_funcionario_path %>

supermercado/app/views/funcionarios/new.html.erb
<h1>Novo Funcionario</h1>

<div class="center jumbotron">
<%= render 'form' %>

<%= link_to 'Voltar', funcionarios_path %>

</div>

supermercado/app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @funcionario.sexo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @funcionario.email %>
</p>

<p>
  <strong>Data:</strong>
  <%= @funcionario.data %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @funcionario.idade %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @funcionario.salario %>
</p>

<%= link_to 'Editar', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Voltar', funcionarios_path %>